input:
    vision: &input_vision
        channel: 3
        width: 64
        height: 16
    motion: &input_motion 2

vision_encoder_module:
    input: *input_vision
    conv:
        - ch: 16
          kernel_size: [3, 10]
          stride: 2
          padding: 1
        - ch: 32
          kernel_size: [3, 10]
          stride: 2
          padding: 1
        - ch: 64
          kernel_size: [3, 10]
          stride: 2
          padding: 1
    fc:
        - input: ~
          output: &enc_out 64

superposition_module:
    input:
        motion: *input_motion
        vision: *enc_out
    hidden: &sp_hidden 128
    
integration_module:
    fc:
        each_input: *sp_hidden
        output: *enc_out

vision_decoder_module:
    fc:
        - input: *enc_out
          output: ~
    conv:
        - ch: 32
          kernel_size: [4, 10]
          stride: 2
          padding: 1
        - ch: 16
          kernel_size: [4, 12]
          stride: 2
          padding: 1
        - ch: 3
          kernel_size: [4, 12]
          stride: 2
          padding: 1
