model:
    name: Autoencoder
    config: default
    mode: ~
runner: AutoencoderRunner
data:
    name: self_random_other_stay
load_state_dict_strict: False
train:
    loss_function: l1_loss
    pretrain:
        exp_config: exp1_l1
        seed: 0
        epoch: 200
    batch_size: 100
    max_epochs: 100
    save_interval: 1
    test_interval: 100
    optimizer: AdamW
    optim_config:
        default:
            lr: 0.001
            weight_decay: 3.
        freeze:
            - vision_encoder
            - share_lns
        per_params:
            - name: bias
              args:
                  weight_decay: 0.0
